language: generic
before_install:
- openssl aes-256-cbc -K $encrypted_952efd7d7538_key -iv $encrypted_952efd7d7538_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 deploy_rsa
- ssh-add deploy_rsa
env:
- PROJECT=ExpressiveCalendar
install:
- cd .. && tar --exclude='./$PROJECT/git' -czvf $PROJECT.tar.gz $PROJECT
- ssh -oStrictHostKeyChecking=no $MACHINE_ADDR 'mkdir -p /var/project'
- scp -oStrictHostKeyChecking=no $PROJECT.tar.gz $MACHINE_ADDR:/var/project/$PROJECT.tar.gz
- ssh -oStrictHostKeyChecking=no $MACHINE_ADDR "cd /var/project && tar -xvzf $PROJECT.tar.gz"
- ssh -oStrictHostKeyChecking=no $MACHINE_ADDR "cd /www/$PROJECT && docker-compose  build"
- ssh -oStrictHostKeyChecking=no $MACHINE_ADDR "docker-compose up -d"
