export const GROUP_HASH = 'GROUP_HASH';
export const GROUP_DATA = 'GROUP_DATA';
export const GROUP_LIST = 'GROUP_LIST';
export const CALENDAR_PRIVACY_LEVEL = 'CALENDAR_PRIVACY_LEVEL';
export const EVENT_PRIVACY_LEVEL = 'EVENT_PRIVACY_LEVEL';
